<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.280">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Introduction to R, RStudio, and quarto</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="01-rstudio-intro_files/libs/clipboard/clipboard.min.js"></script>
<script src="01-rstudio-intro_files/libs/quarto-html/quarto.js"></script>
<script src="01-rstudio-intro_files/libs/quarto-html/popper.min.js"></script>
<script src="01-rstudio-intro_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="01-rstudio-intro_files/libs/quarto-html/anchor.min.js"></script>
<link href="01-rstudio-intro_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="01-rstudio-intro_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="01-rstudio-intro_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="01-rstudio-intro_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="01-rstudio-intro_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Introduction to R, RStudio, and quarto</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="motivation" class="level2">
<h2 class="anchored" data-anchor-id="motivation">Motivation</h2>
<p>Science is a multi-step process: once you’ve designed an experiment and collected data, the real fun begins! This lesson will teach you how to start this process using R and RStudio. We will begin with raw data, perform exploratory analyses, and learn how to plot results graphically. This example starts with a dataset from <a href="https://www.gapminder.org">gapminder.org</a> containing population information for many countries through time. Can you read the data into R? Can you plot the population for Senegal? Can you calculate the average income for countries on the continent of Asia? By the end of these lessons you will be able to do things like plot the populations for all of these countries in under a minute!</p>
</section>
<section id="before-starting-the-workshop" class="level2">
<h2 class="anchored" data-anchor-id="before-starting-the-workshop">Before Starting The Workshop</h2>
<p>Please ensure you have the latest version of R and RStudio installed on your machine. This is important, as some packages used in the workshop may not install correctly (or at all) if R is not up to date.</p>
<ul>
<li><a href="https://www.r-project.org/">Download and install the latest version of R here</a></li>
<li><a href="https://www.rstudio.com/products/rstudio/download/#download">Download and install RStudio here</a></li>
</ul>
</section>
<section id="introduction-to-rstudio" class="level2">
<h2 class="anchored" data-anchor-id="introduction-to-rstudio">Introduction to RStudio</h2>
<p>Welcome to the R portion of the Software Carpentry workshop.</p>
<p>Throughout this lesson, we’re going to teach you some of the fundamentals of the R language as well as some best practices for organizing code for scientific projects that will make your life easier.</p>
<p>We’ll be using RStudio: a free, open-source R Integrated Development Environment (IDE). It provides a built-in editor, works on all platforms (including on servers) and provides many advantages such as integration with version control and project management.</p>
<p><strong>Basic layout</strong></p>
<p>When you first open RStudio, you will be greeted by three panels:</p>
<ul>
<li>The interactive R console/Terminal (entire left)</li>
<li>Environment/History/Connections (tabbed in upper right)</li>
<li>Files/Plots/Packages/Help/Viewer (tabbed in lower right)</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../fig/01-rstudio.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">RStudio layout</figcaption><p></p>
</figure>
</div>
<p>Once you open files, such as R scripts, an editor panel will also open in the top left.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../fig/01-rstudio-script.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">RStudio layout with .R file open</figcaption><p></p>
</figure>
</div>
<blockquote class="blockquote">
<h2 id="r-scripts" class="anchored">R scripts</h2>
<p>Any commands that you write in the R console can be saved in to a file to be re-run again. Files containing R code to be ran in this way are called R scripts. R scripts have <code>.R</code> at the end of their names to let you know what they are. {: .callout}</p>
</blockquote>
</section>
<section id="workflow-within-rstudio" class="level2">
<h2 class="anchored" data-anchor-id="workflow-within-rstudio">Workflow within RStudio</h2>
<p>There are two main ways one can work within RStudio:</p>
<ol type="1">
<li>Test and play within the interactive R console then copy code into a .R file to run later.
<ul>
<li>This works well when doing small tests and initially starting off.</li>
<li>It quickly becomes laborious</li>
</ul></li>
<li>Start writing in a .R file and use RStudio’s short cut keys for the Run command to push the current line, selected lines or modified lines to the interactive R console.
<ul>
<li>This is a great way to start; all your code is saved for later</li>
<li>You will be able to run the file you create from within RStudio or using R’s <code>source()</code> function.</li>
</ul></li>
</ol>
<blockquote class="blockquote">
<h2 id="tip-running-segments-of-your-code" class="anchored">Tip: Running segments of your code</h2>
<p>RStudio offers you great flexibility in running code from within the editor window. There are buttons, menu choices, and keyboard shortcuts. To run the current line, you can 1. click on the <code>Run</code> button above the editor panel, or 2. select “Run Lines” from the “Code” menu, or 3. hit <kbd>Ctrl</kbd>+<kbd>Return</kbd> in Windows or Linux or <kbd>⌘</kbd>+<kbd>Return</kbd> on OS X. (This shortcut can also be seen by hovering the mouse over the button). To run a block of code, select it and then <code>Run</code>. If you have modified a line of code within a block of code you have just run, there is no need to reselect the section and <code>Run</code>, you can use the next button along, <code>Re-run the previous region</code>. This will run the previous code block including the modifications you have made. {: .callout}</p>
</blockquote>
</section>
<section id="introduction-to-r" class="level2">
<h2 class="anchored" data-anchor-id="introduction-to-r">Introduction to R</h2>
<p>Much of your time in R will be spent in the R interactive console. This is where you will run all of your code, and can be a useful environment to try out ideas before adding them to an R script file. This console in RStudio is the same as the one you would get if you typed in <code>R</code> in your command-line environment.</p>
<p>The first thing you will see in the R interactive session is a bunch of information, followed by a “&gt;” and a blinking cursor. In many ways this is similar to the shell environment you learned about during the shell lessons: it operates on the same idea of a “Read, evaluate, print loop”: you type in commands, R tries to execute them, and then returns a result.</p>
</section>
<section id="using-r-as-a-calculator" class="level2">
<h2 class="anchored" data-anchor-id="using-r-as-a-calculator">Using R as a calculator</h2>
<p>The simplest thing you could do with R is to do arithmetic:</p>
<div class="cell" data-layout-align="center">
<pre><code>1 + 100</code></pre>
<p>{: .language-r}</p>
<pre><code>[1] 101</code></pre>
<p>{: .output}</p>
</div>
<p>And R will print out the answer, with a preceding “[1]”. [1] is the index of the first element of the line being printed in the console. For more information on indexing vectors, see <a href="https://swcarpentry.github.io/r-novice-gapminder/06-data-subsetting/index.html">Episode 6: Subsetting Data</a>.</p>
<p>If you type in an incomplete command, R will wait for you to complete it. If you are familiar with Unix Shell’s bash, you may recognize this<br>
behavior from bash.</p>
<pre><code>&gt; 1 +</code></pre>
<p>{: .r}</p>
<pre><code>+</code></pre>
<p>{: .output}</p>
<p>Any time you hit return and the R session shows a “+” instead of a “&gt;”, it means it’s waiting for you to complete the command. If you want to cancel a command you can hit <kbd>Esc</kbd> and RStudio will give you back the “&gt;” prompt.</p>
<blockquote class="blockquote">
<h2 id="tip-canceling-commands" class="anchored">Tip: Canceling commands</h2>
<p>If you’re using R from the command line instead of from within RStudio, you need to use <kbd>Ctrl</kbd>+<kbd>C</kbd> instead of <kbd>Esc</kbd> to cancel the command. This applies to Mac users as well!</p>
<p>Canceling a command isn’t only useful for killing incomplete commands: you can also use it to tell R to stop running code (for example if it’s taking much longer than you expect), or to get rid of the code you’re currently writing.</p>
<p>{: .callout}</p>
</blockquote>
<p>When using R as a calculator, the order of operations is the same as you would have learned back in school.</p>
<p>From highest to lowest precedence:</p>
<ul>
<li>Parentheses: <code>(</code>, <code>)</code></li>
<li>Exponents: <code>^</code> or <code>**</code></li>
<li>Multiply: <code>*</code></li>
<li>Divide: <code>/</code></li>
<li>Add: <code>+</code></li>
<li>Subtract: <code>-</code></li>
</ul>
<div class="cell" data-layout-align="center">
<pre><code>3 + 5 * 2</code></pre>
<p>{: .language-r}</p>
<pre><code>[1] 13</code></pre>
<p>{: .output}</p>
</div>
<p>Use parentheses to group operations in order to force the order of evaluation if it differs from the default, or to make clear what you intend.</p>
<div class="cell" data-layout-align="center">
<pre><code>(3 + 5) * 2</code></pre>
<p>{: .language-r}</p>
<pre><code>[1] 16</code></pre>
<p>{: .output}</p>
</div>
<p>This can get unwieldy when not needed, but clarifies your intentions. Remember that others may later read your code.</p>
<div class="cell" data-layout-align="center">
<pre><code>(3 + (5 * (2 ^ 2))) # hard to read
3 + 5 * 2 ^ 2       # clear, if you remember the rules
3 + 5 * (2 ^ 2)     # if you forget some rules, this might help</code></pre>
<p>{: .language-r}</p>
</div>
<p>The text after each line of code is called a “comment”. Anything that follows after the hash (or octothorpe) symbol <code>#</code> is ignored by R when it executes code.</p>
<p>Really small or large numbers get a scientific notation:</p>
<div class="cell" data-layout-align="center">
<pre><code>2/10000</code></pre>
<p>{: .language-r}</p>
<pre><code>[1] 2e-04</code></pre>
<p>{: .output}</p>
</div>
<p>Which is shorthand for “multiplied by <code>10^XX</code>”. So <code>2e-4</code> is shorthand for <code>2 * 10^(-4)</code>.</p>
<p>You can write numbers in scientific notation too:</p>
<div class="cell" data-layout-align="center">
<pre><code>5e3  # Note the lack of minus here</code></pre>
<p>{: .language-r}</p>
<pre><code>[1] 5000</code></pre>
<p>{: .output}</p>
</div>
</section>
<section id="mathematical-functions" class="level2">
<h2 class="anchored" data-anchor-id="mathematical-functions">Mathematical functions</h2>
<p>R has many built in mathematical functions. To call a function, we can type its name, followed by open and closing parentheses. Functions take arguments as inputs, anything we type inside the parentheses of a function is considered an argument. Depending on the function, the number of arguments can vary from none to multiple. For example:</p>
<div class="cell" data-layout-align="center">
<pre><code>getwd() #returns an absolute filepath</code></pre>
<p>{: .language-r}</p>
</div>
<p>doesn’t require an argument, whereas for the next set of mathematical functions we will need to supply the function a value in order to compute the result.</p>
<div class="cell" data-layout-align="center">
<pre><code>sin(1)  # trigonometry functions</code></pre>
<p>{: .language-r}</p>
<pre><code>[1] 0.841471</code></pre>
<p>{: .output}</p>
</div>
<div class="cell" data-layout-align="center">
<pre><code>log(1)  # natural logarithm</code></pre>
<p>{: .language-r}</p>
<pre><code>[1] 0</code></pre>
<p>{: .output}</p>
</div>
<div class="cell" data-layout-align="center">
<pre><code>log10(10) # base-10 logarithm</code></pre>
<p>{: .language-r}</p>
<pre><code>[1] 1</code></pre>
<p>{: .output}</p>
</div>
<div class="cell" data-layout-align="center">
<pre><code>exp(0.5) # e^(1/2)</code></pre>
<p>{: .language-r}</p>
<pre><code>[1] 1.648721</code></pre>
<p>{: .output}</p>
</div>
<p>Don’t worry about trying to remember every function in R. You can look them up on Google, or if you can remember the start of the function’s name, use the tab completion in RStudio.</p>
<p>This is one advantage that RStudio has over R on its own, it has auto-completion abilities that allow you to more easily look up functions, their arguments, and the values that they take.</p>
<p>Typing a <code>?</code> before the name of a command will open the help page for that command. When using RStudio, this will open the ‘Help’ pane; if using R in the terminal, the help page will open in your browser. The help page will include a detailed description of the command and how it works. Scrolling to the bottom of the help page will usually show a collection of code examples which illustrate command usage. We’ll go through an example later.</p>
</section>
<section id="comparing-things" class="level2">
<h2 class="anchored" data-anchor-id="comparing-things">Comparing things</h2>
<p>We can also do comparisons in R:</p>
<div class="cell" data-layout-align="center">
<pre><code>1 == 1  # equality (note two equals signs, read as "is equal to")</code></pre>
<p>{: .language-r}</p>
<pre><code>[1] TRUE</code></pre>
<p>{: .output}</p>
</div>
<div class="cell" data-layout-align="center">
<pre><code>1 != 2  # inequality (read as "is not equal to")</code></pre>
<p>{: .language-r}</p>
<pre><code>[1] TRUE</code></pre>
<p>{: .output}</p>
</div>
<div class="cell" data-layout-align="center">
<pre><code>1 &lt; 2  # less than</code></pre>
<p>{: .language-r}</p>
<pre><code>[1] TRUE</code></pre>
<p>{: .output}</p>
</div>
<div class="cell" data-layout-align="center">
<pre><code>1 &lt;= 1  # less than or equal to</code></pre>
<p>{: .language-r}</p>
<pre><code>[1] TRUE</code></pre>
<p>{: .output}</p>
</div>
<div class="cell" data-layout-align="center">
<pre><code>1 &gt; 0  # greater than</code></pre>
<p>{: .language-r}</p>
<pre><code>[1] TRUE</code></pre>
<p>{: .output}</p>
</div>
<div class="cell" data-layout-align="center">
<pre><code>1 &gt;= -9 # greater than or equal to</code></pre>
<p>{: .language-r}</p>
<pre><code>[1] TRUE</code></pre>
<p>{: .output}</p>
</div>
<blockquote class="blockquote">
<h2 id="tip-comparing-numbers" class="anchored">Tip: Comparing Numbers</h2>
<p>A word of warning about comparing numbers: you should never use <code>==</code> to compare two numbers unless they are integers (a data type which can specifically represent only whole numbers).</p>
<p>Computers may only represent decimal numbers with a certain degree of precision, so two numbers which look the same when printed out by R, may actually have different underlying representations and therefore be different by a small margin of error (called Machine numeric tolerance).</p>
<p>Instead you should use the <code>all.equal</code> function.</p>
<p>Further reading: <a href="http://floating-point-gui.de/">http://floating-point-gui.de/</a></p>
<p>{: .callout}</p>
</blockquote>
</section>
<section id="variables-and-assignment" class="level2">
<h2 class="anchored" data-anchor-id="variables-and-assignment">Variables and assignment</h2>
<p>We can store values in variables using the assignment operator <code>&lt;-</code>, like this:</p>
<div class="cell" data-layout-align="center">
<pre><code>x &lt;- 1/40</code></pre>
<p>{: .language-r}</p>
</div>
<p>Notice that assignment does not print a value. Instead, we stored it for later in something called a <strong>variable</strong>. <code>x</code> now contains the <strong>value</strong> <code>0.025</code>:</p>
<div class="cell" data-layout-align="center">
<pre><code>x</code></pre>
<p>{: .language-r}</p>
<pre><code>[1] 0.025</code></pre>
<p>{: .output}</p>
</div>
<p>More precisely, the stored value is a <em>decimal approximation</em> of this fraction called a <a href="http://en.wikipedia.org/wiki/Floating_point">floating point number</a>.</p>
<p>Look for the <code>Environment</code> tab in the top right panel of RStudio, and you will see that <code>x</code> and its value have appeared. Our variable <code>x</code> can be used in place of a number in any calculation that expects a number:</p>
<div class="cell" data-layout-align="center">
<pre><code>log(x)</code></pre>
<p>{: .language-r}</p>
<pre><code>[1] -3.688879</code></pre>
<p>{: .output}</p>
</div>
<p>Notice also that variables can be reassigned:</p>
<div class="cell" data-layout-align="center">
<pre><code>x &lt;- 100</code></pre>
<p>{: .language-r}</p>
</div>
<p><code>x</code> used to contain the value 0.025 and now it has the value 100.</p>
<p>Assignment values can contain the variable being assigned to:</p>
<div class="cell" data-layout-align="center">
<pre><code>x &lt;- x + 1 #notice how RStudio updates its description of x on the top right tab
y &lt;- x * 2</code></pre>
<p>{: .language-r}</p>
</div>
<p>The right hand side of the assignment can be any valid R expression. The right hand side is <em>fully evaluated</em> before the assignment occurs.</p>
<p>Variable names can contain letters, numbers, underscores and periods but no spaces. They must start with a letter or a period followed by a letter (they cannot start with a number nor an underscore). Variables beginning with a period are hidden variables. Different people use different conventions for long variable names, these include</p>
<ul>
<li>periods.between.words</li>
<li>underscores_between_words</li>
<li>camelCaseToSeparateWords</li>
</ul>
<p>What you use is up to you, but <strong>be consistent</strong>.</p>
<p>It is also possible to use the <code>=</code> operator for assignment:</p>
<div class="cell" data-layout-align="center">
<pre><code>x = 1/40</code></pre>
<p>{: .language-r}</p>
</div>
<p>But this is much less common among R users. The most important thing is to <strong>be consistent</strong> with the operator you use. There are occasionally places where it is less confusing to use <code>&lt;-</code> than <code>=</code>, and it is the most common symbol used in the community. So the recommendation is to use <code>&lt;-</code>.</p>
<blockquote class="blockquote">
<h2 id="challenge-1" class="anchored">Challenge 1</h2>
<p>Which of the following are valid R variable names? ::: {.cell layout-align=“center”}</p>
<pre><code>min_height
max.height
_age
.mass
MaxLength
min-length
2widths
celsius2kelvin</code></pre>
<p>{: .language-r} :::</p>
<blockquote class="blockquote">
<h2 id="solution-to-challenge-1" class="anchored">Solution to challenge 1</h2>
<p>The following can be used as R variables: ::: {.cell layout-align=“center”}</p>
<pre><code>min_height
max.height
MaxLength
celsius2kelvin</code></pre>
<p>{: .language-r} :::</p>
<p>The following creates a hidden variable: ::: {.cell layout-align=“center”}</p>
<pre><code>.mass</code></pre>
<p>{: .language-r} :::</p>
<p>The following will not be able to be used to create a variable ::: {.cell layout-align=“center”}</p>
<pre><code>_age
min-length
2widths</code></pre>
<p>{: .language-r} ::: {: .solution} {: .challenge}</p>
</blockquote>
</blockquote>
</section>
<section id="vectorization" class="level2">
<h2 class="anchored" data-anchor-id="vectorization">Vectorization</h2>
<p>One final thing to be aware of is that R is <em>vectorized</em>, meaning that variables and functions can have vectors as values. In contrast to physics and mathematics, a vector in R describes a set of values in a certain order of the same data type. For example</p>
<div class="cell" data-layout-align="center">
<pre><code>1:5</code></pre>
<p>{: .language-r}</p>
<pre><code>[1] 1 2 3 4 5</code></pre>
<p>{: .output}</p>
<pre><code>2^(1:5)</code></pre>
<p>{: .language-r}</p>
<pre><code>[1]  2  4  8 16 32</code></pre>
<p>{: .output}</p>
<pre><code>x &lt;- 1:5
2^x</code></pre>
<p>{: .language-r}</p>
<pre><code>[1]  2  4  8 16 32</code></pre>
<p>{: .output}</p>
</div>
<p>This is incredibly powerful; we will discuss this further in an upcoming lesson.</p>
</section>
<section id="managing-your-environment" class="level2">
<h2 class="anchored" data-anchor-id="managing-your-environment">Managing your environment</h2>
<p>There are a few useful commands you can use to interact with the R session.</p>
<p><code>ls</code> will list all of the variables and functions stored in the global environment (your working R session):</p>
<div class="cell" data-layout-align="center">
<pre><code>ls()</code></pre>
<p>{: .language-r}</p>
</div>
<div class="cell" data-layout-align="center">
<pre><code>[1] "x" "y"</code></pre>
<p>{: .output}</p>
</div>
<blockquote class="blockquote">
<h2 id="tip-hidden-objects" class="anchored">Tip: hidden objects</h2>
<p>Like in the shell, <code>ls</code> will hide any variables or functions starting with a “.” by default. To list all objects, type <code>ls(all.names=TRUE)</code> instead</p>
<p>{: .callout}</p>
</blockquote>
<p>Note here that we didn’t give any arguments to <code>ls</code>, but we still needed to give the parentheses to tell R to call the function.</p>
<p>If we type <code>ls</code> by itself, R prints a bunch of code instead of a listing of objects.</p>
<div class="cell" data-layout-align="center">
<pre><code>ls</code></pre>
<p>{: .language-r}</p>
<pre><code>function (name, pos = -1L, envir = as.environment(pos), all.names = FALSE, 
    pattern, sorted = TRUE) 
{
    if (!missing(name)) {
        pos &lt;- tryCatch(name, error = function(e) e)
        if (inherits(pos, "error")) {
            name &lt;- substitute(name)
            if (!is.character(name)) 
                name &lt;- deparse(name)
            warning(gettextf("%s converted to character string", 
                sQuote(name)), domain = NA)
            pos &lt;- name
        }
    }
    all.names &lt;- .Internal(ls(envir, all.names, sorted))
    if (!missing(pattern)) {
        if ((ll &lt;- length(grep("[", pattern, fixed = TRUE))) &amp;&amp; 
            ll != length(grep("]", pattern, fixed = TRUE))) {
            if (pattern == "[") {
                pattern &lt;- "\\["
                warning("replaced regular expression pattern '[' by  '\\\\['")
            }
            else if (length(grep("[^\\\\]\\[&lt;-", pattern))) {
                pattern &lt;- sub("\\[&lt;-", "\\\\\\[&lt;-", pattern)
                warning("replaced '[&lt;-' by '\\\\[&lt;-' in regular expression pattern")
            }
        }
        grep(pattern, all.names, value = TRUE)
    }
    else all.names
}
&lt;bytecode: 0x138c24a48&gt;
&lt;environment: namespace:base&gt;</code></pre>
<p>{: .output}</p>
</div>
<p>What’s going on here?</p>
<p>Like everything in R, <code>ls</code> is the name of an object, and entering the name of an object by itself prints the contents of the object. The object <code>x</code> that we created earlier contains 1, 2, 3, 4, 5:</p>
<div class="cell" data-layout-align="center">
<pre><code>x</code></pre>
<p>{: .language-r}</p>
<pre><code>[1] 1 2 3 4 5</code></pre>
<p>{: .output}</p>
</div>
<p>The object <code>ls</code> contains the R code that makes the <code>ls</code> function work! We’ll talk more about how functions work and start writing our own later.</p>
<p>You can use <code>rm</code> to delete objects you no longer need:</p>
<div class="cell" data-layout-align="center">
<pre><code>rm(x)</code></pre>
<p>{: .language-r}</p>
</div>
<p>If you have lots of things in your environment and want to delete all of them, you can pass the results of <code>ls</code> to the <code>rm</code> function:</p>
<div class="cell" data-layout-align="center">
<pre><code>rm(list = ls())</code></pre>
<p>{: .language-r}</p>
</div>
<p>In this case we’ve combined the two. Like the order of operations, anything inside the innermost parentheses is evaluated first, and so on.</p>
<p>In this case we’ve specified that the results of <code>ls</code> should be used for the <code>list</code> argument in <code>rm</code>. When assigning values to arguments by name, you <em>must</em> use the <code>=</code> operator!!</p>
<p>If instead we use <code>&lt;-</code>, there will be unintended side effects, or you may get an error message:</p>
<div class="cell" data-layout-align="center">
<pre><code>rm(list &lt;- ls())</code></pre>
<p>{: .language-r}</p>
<pre><code>Error in rm(list &lt;- ls()): ... must contain names or character strings</code></pre>
<p>{: .error}</p>
</div>
<blockquote class="blockquote">
<h2 id="tip-warnings-vs.-errors" class="anchored">Tip: Warnings vs.&nbsp;Errors</h2>
<p>Pay attention when R does something unexpected! Errors, like above, are thrown when R cannot proceed with a calculation. Warnings on the other hand usually mean that the function has run, but it probably hasn’t worked as expected.</p>
<p>In both cases, the message that R prints out usually give you clues how to fix a problem.</p>
<p>{: .callout}</p>
</blockquote>
</section>
<section id="r-packages" class="level2">
<h2 class="anchored" data-anchor-id="r-packages">R Packages</h2>
<p>It is possible to add functions to R by writing a package, or by obtaining a package written by someone else. As of this writing, there are over 10,000 packages available on CRAN (the comprehensive R archive network). R and RStudio have functionality for managing packages:</p>
<ul>
<li>You can see what packages are installed by typing <code>installed.packages()</code></li>
<li>You can install packages by typing <code>install.packages("packagename")</code>, where <code>packagename</code> is the package name, in quotes.</li>
<li>You can update installed packages by typing <code>update.packages()</code></li>
<li>You can remove a package with <code>remove.packages("packagename")</code></li>
<li>You can make a package available for use with <code>library(packagename)</code></li>
</ul>
<p>Packages can also be viewed, loaded, and detached in the Packages tab of the lower right panel in RStudio. Clicking on this tab will display all of the installed packages with a checkbox next to them. If the box next to a package name is checked, the package is loaded and if it is empty, the package is not loaded. Click an empty box to load that package and click a checked box to detach that package.</p>
<p>Packages can be installed and updated from the Package tab with the Install and Update buttons at the top of the tab.</p>
<blockquote class="blockquote">
<h2 id="challenge-2" class="anchored">Challenge 2</h2>
<p>What will be the value of each variable after each statement in the following program?</p>
<div class="cell" data-layout-align="center">
<pre><code>mass &lt;- 47.5
age &lt;- 122
mass &lt;- mass * 2.3
age &lt;- age - 20</code></pre>
<p>{: .language-r}</p>
</div>
<blockquote class="blockquote">
<h2 id="solution-to-challenge-2" class="anchored">Solution to challenge 2</h2>
<div class="cell" data-layout-align="center">
<pre><code>mass &lt;- 47.5</code></pre>
<p>{: .language-r}</p>
</div>
<p>This will give a value of 47.5 for the variable mass</p>
<div class="cell" data-layout-align="center">
<pre><code>age &lt;- 122</code></pre>
<p>{: .language-r}</p>
</div>
<p>This will give a value of 122 for the variable age</p>
<div class="cell" data-layout-align="center">
<pre><code>mass &lt;- mass * 2.3</code></pre>
<p>{: .language-r}</p>
</div>
<p>This will multiply the existing value of 47.5 by 2.3 to give a new value of 109.25 to the variable mass.</p>
<div class="cell" data-layout-align="center">
<pre><code>age &lt;- age - 20</code></pre>
<p>{: .language-r}</p>
</div>
<p>This will subtract 20 from the existing value of 122 to give a new value of 102 to the variable age. {: .solution} {: .challenge}</p>
</blockquote>
</blockquote>
<blockquote class="blockquote">
<h2 id="challenge-3" class="anchored">Challenge 3</h2>
<p>Run the code from the previous challenge, and write a command to compare mass to age. Is mass larger than age?</p>
<blockquote class="blockquote">
<h2 id="solution-to-challenge-3" class="anchored">Solution to challenge 3</h2>
<p>One way of answering this question in R is to use the <code>&gt;</code> to set up the following: ::: {.cell layout-align=“center”}</p>
<pre><code>mass &gt; age</code></pre>
<p>{: .language-r}</p>
<pre><code>[1] TRUE</code></pre>
<p>{: .output} ::: This should yield a boolean value of TRUE since 109.25 is greater than 102. {: .solution} {: .challenge}</p>
</blockquote>
</blockquote>
<blockquote class="blockquote">
<h2 id="challenge-4" class="anchored">Challenge 4</h2>
<p>Clean up your working environment by deleting the mass and age variables.</p>
<blockquote class="blockquote">
<h2 id="solution-to-challenge-4" class="anchored">Solution to challenge 4</h2>
<p>We can use the <code>rm</code> command to accomplish this task ::: {.cell layout-align=“center”}</p>
<pre><code>rm(age, mass)</code></pre>
<p>{: .language-r} ::: {: .solution} {: .challenge}</p>
</blockquote>
</blockquote>
<blockquote class="blockquote">
<h2 id="challenge-5" class="anchored">Challenge 5</h2>
<p>Install the following packages: <code>ggplot2</code>, <code>plyr</code>, <code>gapminder</code></p>
<blockquote class="blockquote">
<h2 id="solution-to-challenge-5" class="anchored">Solution to challenge 5</h2>
<p>We can use the <code>install.packages()</code> command to install the required packages. ::: {.cell layout-align=“center”}</p>
<pre><code>install.packages("ggplot2")
install.packages("plyr")
install.packages("gapminder")</code></pre>
<p>{: .language-r} :::</p>
<p>An alternate solution, to install multiple packages with a single <code>install.packages()</code> command is: ::: {.cell layout-align=“center”}</p>
<pre><code>install.packages(c("ggplot2", "plyr", "gapminder"))</code></pre>
<p>{: .language-r} ::: {: .solution} {: .challenge}</p>
</blockquote>
</blockquote>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>