project:
  type: book

book:
  title: "Software Carpentry R Workshop"
  subtitle: "University of Utah, May 17-18"
  chapters:
    - index.qmd
    - 01-rstudio-quarto.qmd
    - 02-project-intro.qmd
    - 03-r-intro.qmd
    - 04-vectors_types.qmd
    - 05-subsetting-vectors.qmd
    - 06-vectorization.qmd
    - 07-subsetting-data-frames.qmd
    - 08-dplyr.qmd
    - 09-plot-ggplot2.qmd
    - 10-functions.qmd
    - 11-lists.qmd
    - 12-iteration.qmd
    - 13-tidyr.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



